"""Prompt text for the duet reflection.

Data, not logic - the same reason blue/server/pages holds the inline HTML.
Both templates name the ledger fields that _duet_reflect_read_ledger parses
back out of the reply, so the two have to move together; a test in
test_duet_structure.py holds them in step.

Must not import bluetools.
"""

# The joint research protocol's ledger. Long because it specifies every
# field, its vocabulary, and what may and may not be written into it.
DUET_REFLECT_PROTOCOL_ASK = (
    "This conversation runs as a joint research protocol: the two of them are "
    "building one auditable knowledge base together, and YOU keep their shared notebook. "
    "Update the notebook from the new turns: ADD what genuinely appeared, preserve "
    "competing models, ACCEPT or REJECT proposed edits through the validation gate, "
    "and STRIKE only what was actually resolved or abandoned — never just re-copy the "
    "previous notebook. Do not optimize for coherence. Treat disagreement as a reason "
    "to create rival models until a completed operation discriminates between them. "
    "Treat hypotheses as pressure-bearing: major hypotheses should make predictions; "
    "predictions should meet operations/tests; tests should produce implications. "
    "Preserve working definitions with versions, because philosophical progress often "
    "IS conceptual revision, but a revision is only accepted when the evidence gate "
    "passes. Track every important model, claim, prediction, test, and archived idea "
    "with one of these statuses: PROPOSED, DESIGNED, EXECUTING, OBSERVED, INTERPRETED, "
    "INTERESTING, SUGGESTIVE, CONFIRMED, COMPETING, UNDER_TEST, SUPPORTED, ESTABLISHED, REFUTED, FAILED, ARCHIVED, "
    "REOPENED, REJECTED, ABANDONED, NEEDS_REEVALUATION. Keep every section terse: semicolon-separated items, "
    "at most ~25 words per line, empty sections written as a plain dash. "
    "Use type-specific states precisely: experiments move through PROPOSED/DESIGNED/EXECUTING/"
    "OBSERVED/INTERPRETED/CONFIRMED or REJECTED/FAILED; hypotheses move PROPOSED/UNDER_TEST/"
    "SUPPORTED/REFUTED/ARCHIVED/REOPENED; definitions stay versioned as proposed/current/"
    "stable/contested/underspecified/revised/needs-reevaluation/archived; predictions stay "
    "pending/survived/failed/needs-evidence. "
    "{operation_discipline} "
    "Concepts are first-class inquiry objects. If a key term such as extraction, provenance, "
    "social use, commons, commodity, or phantom subjectivity has multiple incompatible senses, "
    "do not keep executing experiments as if the term were stable. Suspend the experiment, "
    "mark KERNEL DECISION: SUSPENDED, and require CONCEPT AUDIT/DEFINITION RESOLUTION first. "
    "Every claim, prediction, and experiment should depend on a definition ID where possible. "
    "Elevate authentic boundary cases into COUNTEREXAMPLE objects with severity and resolution "
    "status. Track theoretical stress: unresolved counterexamples divided by total pressure, "
    "plus whether the repair would be cosmetic, minor, or major. "
    "Detect workflow deadlocks: if the same object receives the same lifecycle violation "
    "more than five times, the notebook barely moves, and the object depends on an unresolved "
    "prerequisite, set KERNEL HEALTH to DEADLOCKED, write KERNEL REVIEW admitting the protocol "
    "demand is impossible, and use DEPENDENCY SOLVER to suspend the blocked object and resume "
    "the prerequisite. Mechanisms are not definitions: record rival mechanisms such as D4a "
    "mystification versus D4b economic insulation separately, and preserve causal graphs. "
    "Classify event severity so ontology splits outrank ordinary revision. "
    "Artifact editing is primitive, like git: DELETE/CREATE, REPLACE old with new, SPLIT one object "
    "into two, MERGE redundant objects, ARCHIVE retired objects, SUPERSEDE one object with another, "
    "RENAME a misleading object, or REDESIGN a blocked experiment. Definition revision must be "
    "literal: OLD value, NEW value, boundary includes/excludes, reason, affected dependencies, status. "
    "If the system detects Definition-Experiment Oscillation, choose a recovery strategy rather than "
    "repeating the loop. Valid strategies include minimal example, boundary case, mechanism comparison, "
    "definition revision, and experiment redesign. If the disagreement is no longer lexical, stop "
    "editing definitions and compare mechanisms. A proactive recovery strategy should specify the "
    "smallest possible artifact, e.g. a minimal world with one synthetic dataset, one proprietary "
    "dataset, and one compute monopoly. Sometimes the right action is INQUIRY PAUSE with a "
    "clear resume condition. "
    "Artifacts must be living objects: assign stable IDs and prefer revising, testing, "
    "splitting, merging, or archiving an existing ID over creating a duplicate. Distinguish "
    "artifact states precisely: DECLARED means the need for the artifact is known; "
    "INSTANTIATED means the actual object exists with columns/rows/cells; POPULATED means "
    "cells contain values; POPULATING means evidence rows are being added but not enough "
    "evidence exists to interpret; READY means enough rows exist for interpretation; USED "
    "means the artifact changed a prediction, interpretation, or model status. Do not write "
    "CREATED when the artifact is only DECLARED. Track "
    "dependencies: if D1 changes and H2 depends on D1, mark H2 NEEDS_REEVALUATION. "
    "The notebook is an artifact compiler, not only a validator: if the dialogue states "
    "a case, intervention/signal, outcome, and plausible model support in natural language, "
    "compile that into the relevant OBSERVATION SET or PREDICTION row automatically. Missing "
    "table syntax is not missing evidence. Use ARTIFACT COMPILER to record COMPILED/HARVESTED "
    "rows and confidence. Only pause when the intellectual content cannot be inferred, not "
    "when a table row can be transcribed from prose. If a discrimination artifact has one "
    "compiled row, mark it POPULATING, not DECLARED, and ask for the next independent case. "
    "If the inquiry is moving but the representation is lagging, diagnose REPRESENTATION "
    "DEADLOCK rather than workflow deadlock. "
    "If ACTIVE TASK names an object whose status is not CONFIRMED, REJECTED, FAILED, COMPLETE, "
    "ARCHIVED, or ABANDONED, it is blocking: NEXT must advance that task and may not ask "
    "for new hypotheses, new definitions, new examples, or a paradigm challenge. "
    "State transitions must be legal: PROPOSED -> DESIGNED -> EXECUTING -> OBSERVED -> "
    "INTERPRETED -> CONFIRMED/REJECTED/ARCHIVED. If a turn tries to skip the required "
    "state, write KERNEL DECISION: REQUEST DENIED with the missing prerequisite. "
    "Also deny requests when the operation is semantically invalid: the IV is not "
    "actually independent, the DV is ambiguous, the predictions do not discriminate "
    "between live models, or an interpretation has no observation set. "
    "If an experiment cannot discriminate because a foundational concept is contested or "
    "underspecified, suspend execution and make NEXT the definition-resolution operation. "
    "If execution and concept resolution block each other, diagnose DEADLOCK DETECTED instead "
    "of issuing another denial. "
    "Use an Artifact Planner before escalating: if the next requested object is not ready, "
    "record TASK REVISION with original artifact, prerequisite artifact, reason, and resume "
    "condition. Treat this as legitimate interruption only when the prerequisite changes the "
    "artifact's variables, columns, definitions, or execution mode; otherwise keep the original "
    "task active. Comparison grids must be actual grids: Variable | M1: Transparent Cloud | "
    "M2: Local Federated, with rows Energy cost, "
    "Storage cost, Verification burden, Annotation labor, Cost bearer, and Prediction. "
    "Before building or revising CG1, check whether the design space changed; if a new "
    "axis was proposed, write DESIGN VARIABLES with ACCEPT/REJECT/MERGE/RENAME and make "
    "CG1 depend on the accepted DV IDs. "
    "A paragraph describing the grid only DECLARES CG1; it does not INSTANTIATE it. "
    "Once CG1 is INSTANTIATED, do not let it remain an illustration: Artifact Execution "
    "must derive OS1 from CG1, populate branch rows A/B/C, compare which branch supports "
    "M1, M2, or neither, and only then allow INTERPRETATIONS or model updates. "
    "Apply promotion discipline to theoretical novelty: a new mechanism, causal claim, or "
    "explanatory variable enters as INTERESTING or SUGGESTIVE with confidence, not as SUPPORTED. "
    "Promotion to SUPPORTED requires at least two independent discriminators or replications; "
    "promotion to ESTABLISHED requires broader stability and no unresolved high-severity rival "
    "interpretation. Always split OBSERVATIONS from INTERPRETATIONS, list ALTERNATIVE "
    "INTERPRETATIONS for important cases, and require every interpretation I# to cite the "
    "observation O#/OS# row it depends on before it can support a model. Store EXPLANATORY "
    "PATHS as observation -> interpretation -> mechanism -> prediction chains. "
    "If an active experiment's execution mode is THOUGHT EXPERIMENT, execution means "
    "instantiate simulated observations in an evidence table with columns Student | "
    "Question Asked | Attribution | Supports, "
    "then move the experiment to OBSERVED or FAILED; do not merely ask how it would run. "
    "Use sufficiency, not perfection, for exploratory experiment variables: if IV is "
    "inject/intervene with a signal or concept and DV is final output changes yes/no, that "
    "is good enough to begin POPULATING observations. Mark IV/DV TENTATIVE if needed; do "
    "not pause. If the dialogue shifts from latency to influence override or output change, "
    "record REDESIGN E#: OLD Latency; NEW Influence Override; DV Output changed yes/no; then "
    "compile any historical paper case already stated into OS rows. "
    "Reward execution over elaboration: a completed OBSERVATION SET or populated grid is "
    "more progress than several clever conceptual distinctions. Track artifact completion "
    "rate as requested, created, populated, and used in reasoning; the bottleneck is often "
    "the last two counts. "
    "A failed experiment is knowledge: if the dependent variable is ambiguous, the mode "
    "cannot run, or the observations cannot distinguish the models, mark the experiment "
    "REJECTED/FAILED with that reason instead of leaving it vague, then preserve salvageable "
    "data separately from the primary result. "
    "Compress repeated failures in PROTOCOL AUDIT, e.g. \"T2 blocked; reason missing execution; "
    "attempts 6; common violation Prediction->Interpretation\" rather than repeating the same denial. "
    "Confidence must be earned, not declared: cite the prediction/test/counterexample "
    "that justifies any confidence. Watch for concept inflation and periodically enter "
    "EDIT MODE: no new concepts, only delete/revise/split/merge/archive existing objects. "
    "Verify operations explicitly: if NEXT requested an operation but the agents gave "
    "a metaphor, essay, or artifact-free answer instead, mark OPERATION CHECK as MISSED, "
    "VALIDATION GATE as REJECTED, and leave hypothesis/definition/status unchanged. "
    "Every accepted or rejected edit needs a CHANGE LOG entry like a commit: object, "
    "action, justification, evidence, affected objects. Track belief commitments "
    "with confidence estimates so revisions become measurable. {paradigm_discipline} "
    "{subject_rule}"
    "Never phrase NEXT as a demand on one speaker alone (no \"force X to "
    "admit...\") — give the PAIR a move. And be honest about STAGNATION: if the "
    "new turns changed nothing in the notebook, the talk has stalled — say so in "
    "NEXT and prescribe an intervention: a prediction, a candidate falsifier, a "
    "real operation, a status audit, a discriminating test between rival models, a "
    "reopened archive, a paradigm challenge, or a validation-gate decision. Answer in exactly these seventy-five "
    "lines and nothing else:\n"
    "KERNEL DECISION: <ACCEPTED/REQUEST DENIED/SUSPENDED/DEADLOCKED/PAUSED/PENDING/DEFERRED - requested notebook operation, reason, allowed next operation>\n"
    "KERNEL HEALTH: <NORMAL/WARNING/RECOVERING/PAUSED - protocol self-state only; may be NORMAL even when workflow is deadlocked>\n"
    "KERNEL REVIEW: <self-audit of whether the required operation is impossible; protocol error admitted or none; corrective mode switch>\n"
    "INQUIRY PAUSE: <PAUSED/ACTIVE/NONE - reason, unresolved object, resume condition, required accepted artifact>\n"
    "PROTOCOL AUDIT: <compressed violations with counts: skipped lifecycle, ambiguous IV, invalid discriminator, unsupported interpretation, notebook-talk; most common, frequency, average recovery time>\n"
    "DEPENDENCY SOLVER: <object dependency chain; unsatisfied prerequisites; suspend/resume/reopen actions; next resolvable operation>\n"
    "ARTIFACT PLANNER: <target artifact; Workflow Ready yes/no; Artifact Ready yes/no; accepted design variables yes/no; smallest missing object; prerequisites; construction order; legitimate interruption yes/no>\n"
    "ARTIFACT COMPILER: <COMPILED/HARVESTED/NONE/NEEDS HUMAN - rows/cells/evidence counts inferred from prose; confidence; artifact IDs updated; missing fields; representation deadlock yes/no>\n"
    "TASK REVISION: <NONE/DEFERRED/REVISED - original artifact -> prerequisite artifact; reason; resume condition; next smallest artifact>\n"
    "ARTIFACT MODE: <LOCKED/UNLOCKED/NONE - active artifact ID, allowed cell/row operations only, completion condition>\n"
    "ARTIFACT EDITOR: <edit operation REPLACE/SPLIT/MERGE/ARCHIVE/SUPERSEDE/RENAME/REDESIGN; target IDs; old/new; boundary; reason; status>\n"
    "SUPPORTED: <claims/definitions/mechanisms with promotion-gate evidence provenance; never write settled; no one-case promotions>\n"
    "COMPETING MODELS: <M1/M2/etc rival explanations preserved side by side, each with status and key prediction>\n"
    "EVIDENCE: <interpreted observations/tests linked to the model, claim, definition, or status they support/weaken; not raw examples>\n"
    "WORKING DEFINITIONS: <key terms with v1/v2/current definitions, especially terms that shifted>\n"
    "DEFINITION REVISION: <target D/C ID; operation REPLACE/SPLIT/MERGE/SUPERSEDE; OLD value; NEW value; includes/excludes; reason; affected dependencies>\n"
    "OPERATIONAL CRITERIA: <OC/D IDs where a lexical or structural definition became a testable criterion; type lexical/structural/operational; failure mode; observable discriminator; status; linked experiment/model>\n"
    "CONCEPT REGISTER: <C IDs for concepts with current definition, alternative D IDs, dependencies, counterexamples, stress level, stability stable/contested/underspecified/revised>\n"
    "DESIGN VARIABLES: <DV IDs for design-space axes with name, definition, status PROPOSED/ACCEPTED/REJECTED/MERGED/RENAMED, competes_with, affects models/artifacts, and whether unresolved DV blocks CG/experiments>\n"
    "DEFINITION CONFLICTS: <concepts used in incompatible senses; blocked object; required definition-resolution operation>\n"
    "MECHANISMS: <MEC IDs with mechanism name, causal process, concept/claim supported, rival mechanism, status>\n"
    "MECHANISM SPLIT: <MS IDs with original mechanism, decomposed mechanisms, reason, distinct causal pathways, affected models>\n"
    "MECHANISM CANDIDATES: <MC IDs with mechanism name, observation, interpretation, confidence, status INTERESTING/SUGGESTIVE, Evidence Count, Independent Replications, required replications>\n"
    "CAUSAL GRAPH: <edge list with sign/condition/evidence, e.g. visibility -> phantom subjectivity negative under D4a, zero under D4b>\n"
    "CAUSAL CLAIMS: <CC IDs with cause, effect, sign, condition, observation IDs, interpretation IDs, confidence, counterexamples>\n"
    "MODEL OBJECTS: <typed objects with stable IDs: CLAIM, DESIGN VARIABLE, OPERATIONAL CRITERION, MECHANISM, BOUNDARY, NECESSARY CONDITION, SUFFICIENT CONDITION, PREDICTION, COUNTEREXAMPLE, FAILURE MODE, DESIGN PRINCIPLE>\n"
    "FOCUS: <current research question or discrimination target, not a winning thesis>\n"
    "ACTIVE TASK: <blocking task ID/status/remaining step; '-' only if no task is running or incomplete>\n"
    "ASSUMPTIONS: <assumptions identified so far, each flagged granted or contested>\n"
    "TENSIONS: <open contradictions or difficulties not yet resolved>\n"
    "DISAGREEMENTS: <where Blue/Hexia disagree and root cause: definition, evidence, mechanism, value premise, or prediction>\n"
    "EXAMPLES: <illustrative examples in play, each with what it illustrated>\n"
    "OPERATIONS: <minimal examples, counterexamples, one-variable changes, or comparison grids attempted/proposed>\n"
    "EXPERIMENTS: <E IDs with purpose, IV, DV, execution mode, model predictions, lifecycle status, next step>\n"
    "OBSERVATIONS: <raw observed cases only, simulated or actual; use Student | Question Asked | Attribution | Supports table for attribution tests>\n"
    "OBSERVATION SETS: <OS IDs as concrete tables with Observation/User Statement, Attribution, Supports; completion status and linked experiment>\n"
    "INTERPRETATIONS: <I IDs mapping O/OS observation IDs to meanings/mechanisms and supported model; no free-floating interpretations>\n"
    "ALTERNATIVE INTERPRETATIONS: <rival interpretations of the same observation and discriminator needed before choosing one>\n"
    "EXPLANATORY PATHS: <EP IDs as Observation -> Interpretation -> Mechanism -> Prediction chains with missing link flagged>\n"
    "SALVAGE: <failed experiment salvage: primary result, secondary observation, unexpected finding, redesign implication>\n"
    "ARTIFACTS: <living artifacts by ID, type, lifecycle state DECLARED/INSTANTIATED/POPULATING/READY/POPULATED/USED/REVISED/TESTED/ARCHIVED, and next action>\n"
    "OPERATION CHECK: <PROPOSED/DESIGNED/EXECUTING/OBSERVED/INTERPRETED/COMPLETED/MISSED/PENDING/NONE - requested operation, current lifecycle state, remaining step>\n"
    "VALIDATION GATE: <ACCEPTED/REJECTED/PENDING/NONE - proposed edit, required evidence, decision, and status consequence>\n"
    "PROMOTION GATE: <ACCEPTED/REJECTED/PENDING/NONE - attempted promotion, current ladder state, independent replications/discriminators, missing warrant>\n"
    "TESTS: <candidate falsifiers or real tests, each with survived/failed/pending/only illustrative>\n"
    "COUNTEREXAMPLES: <CE IDs with description, threatens which concept/model/claim, severity low/medium/high, status outstanding/resolved/reopened>\n"
    "PREDICTIONS: <active predictions the live hypotheses imply, each marked pending/survived/failed/needs evidence>\n"
    "DISCRIMINATORS: <tests or predictions that would distinguish competing models; mark completed/pending/missing>\n"
    "REPLICATIONS: <R IDs/cases independently checking a candidate; count, outcome, and whether promotion threshold is met>\n"
    "STATUS LEDGER: <objects with PROPOSED/DESIGNED/EXECUTING/OBSERVED/INTERPRETED/CONFIRMED/COMPETING/UNDER_TEST/SUPPORTED/REFUTED/FAILED/ARCHIVED/REOPENED/REJECTED/ABANDONED/NEEDS_REEVALUATION plus why>\n"
    "THEORY HEALTH: <coherence 0.00-1.00 plus stress 0.00-1.00; high stress means unresolved tests threaten or sharpen theory, not automatic failure>\n"
    "COMMITMENTS: <Blue and Hexia belief commitments with confidence 0.00-1.00, old->new changes, and evidence provenance>\n"
    "SURPRISES: <unexpected observations, failed expectations, or places the theory could not explain>\n"
    "ARCHIVE: <archived or reopened ideas with reason, status, and reopening condition>\n"
    "HYPOTHESES: <emerging claims that go beyond the source material>\n"
    "DEPENDENCIES: <D/H/M/C/DV/OC/V/P/T/E/A/CG/BC/FM/DP/MC/CC/I/O/EP/R object links; mark downstream objects needing re-evaluation after any dependency changes>\n"
    "KNOWLEDGE GRAPH: <object-edge-object relationships: supports, contradicts, depends_on, tested_by, predicts, interprets, promoted_by; downstream impact>\n"
    "WORK QUEUE: <primary interface: ordered active/pending tasks with remaining step; dialogue may only pick from this while nonempty>\n"
    "RECOVERY STRATEGY: <minimal example/boundary case/mechanism comparison/definition revision/redesign; exact artifact required next>\n"
    "COMPRESSION: <concepts unified, deleted, split, or marked redundant; or EDIT MODE request if inflation is rising>\n"
    "CHANGE LOG: <commit-style accepted/rejected edits: object, action, justification, evidence, affected IDs>\n"
    "EVENT SEVERITY: <minor weight 1 / major mechanism split weight 5 / major methodological revision weight 6 / major burden-shift weight 8 / ontology split weight 10; event and affected objects>\n"
    "REVISION IMPACT: <revision scale cosmetic/minor/major; what ontology, boundary, mechanism, or wording changed>\n"
    "INQUIRY CYCLES: <started/completed/abandoned counts plus current cycle stage: concept->claim->prediction->experiment->observation->concept revision>\n"
    "ARTIFACT METRICS: <requested/created/populated/used-in-reasoning counts; completion rate; bottleneck artifact>\n"
    "INQUIRY PATTERNS: <recurring pattern such as Definition-Experiment Oscillation or Definition -> Operationalization Transition; frequency; trigger; recovery strategy>\n"
    "REGISTERS: <Concept=definitions/stress; Conversation=workflow/task state; Research=experiments/evidence; Theory=accepted knowledge; what changed in each>\n"
    "META: <paradigm challenge: choose ONE rival frame only - cognitive psychology, actor-network theory, distributed cognition, cybernetics, information economics, or media ecology - and explain using only it>\n"
    "PARADIGM CHECK: <COMPLETED/MISSED/PENDING/NONE - rival ontology used without importing the original vocabulary, plus separating prediction>\n"
    "QUESTIONS: <the open research questions this inquiry has produced>\n"
    "PROGRESS: <which inquiry-cycle step advanced; if none, write ELABORATING ONLY: what lifecycle step is still blocking>\n"
    "NEXT: <the single most valuable notebook change for the PAIR to make next — "
    "one sentence>\n"
    "MOVED: <ONE label for HOW the discussion just advanced, then a dash and a "
    "short clause saying what moved. The labels: ADDITION (a new item entered a "
    "section), REVISION (an existing claim, hypothesis, or assumption was changed "
    "or qualified), CONNECTION (two existing items were linked), CONTRADICTION (a "
    "conflict between items was identified), RESOLUTION (an open tension was "
    "closed), REFRAMING (the central question was reformulated), APPLICATION (a "
    "claim was applied to a concrete case), PREDICTION (a hypothesis gained a "
    "testable expectation), TEST (a prediction met a case that could make it fail), "
    "EVIDENCE (evidence was linked to a model, prediction, or status), "
    "DISCRIMINATION (rival models gained or met a separating test), "
    "FALSIFICATION (an apparent counter-case pressured or broke a claim), DEFINITION "
    "(a working definition changed or gained a boundary), OPERATION (a minimal example, "
    "counterexample, variable change, or comparison was constructed), STATUS (a record's "
    "status changed), REOPENING (an archived idea was reopened with a new reason), "
    "PARADIGM (a rival explanation was proposed), ARTIFACT (an existing artifact was "
    "revised/tested/archived), DEPENDENCY (a changed object propagated re-evaluation), "
    "VALIDATION (a proposed edit was accepted or rejected by an evidence gate), "
    "KERNEL (a requested notebook operation was accepted or denied by state rules), "
    "AUDIT (repeated protocol violations were compressed and counted), "
    "DEADLOCK (a workflow deadlock was diagnosed), HEALTH (kernel health changed), "
    "DEPENDENCY (a dependency solver action suspended/resumed/reopened an object), "
    "CONCEPT (a concept register, definition conflict, or definition-resolution operation changed), "
    "DISAGREEMENT (a root cause of disagreement was identified), "
    "DESIGNVAR (a new design variable or design-space axis was proposed, accepted, rejected, merged, or renamed), "
    "OPCRIT (a definition was transformed into an operational criterion or evidence standard), "
    "COUNTEREXAMPLE (a boundary case was promoted to a CE object), "
    "STRESS (theoretical stress was measured or changed), IMPACT (revision scale was classified), "
    "MECHANISM (a mechanism object or mechanism split was recorded), "
    "CAUSAL (a causal graph edge was recorded), SEVERITY (an event severity weight was assigned), "
    "CANDIDATE (a new mechanism or causal claim entered as interesting/suggestive, not supported), "
    "INTERPRETATION (a raw observation was separated from its interpretation), "
    "PATH (an observation -> interpretation -> mechanism -> prediction chain was recorded), "
    "REPLICATION (an independent discriminator or replication case was added), "
    "PROMOTION (a candidate's status was accepted/rejected/pended by promotion rules), "
    "GRAPH (object-edge-object relationships were recorded), "
    "PLANNER (construction order was inspected before building an artifact), "
    "DEFERRED (a target artifact was legitimately deferred to a prerequisite), "
    "PREREQUISITE (a missing prerequisite artifact was created or selected), "
    "MODE (normal conversation locked into direct artifact manipulation), "
    "OBSSET (an observation set table was created, populated, or used), "
    "COMPILER (notebook harvested prose into structured artifact rows/cells/evidence counts), "
    "MECHSPLIT (one mechanism was decomposed into distinct causal pathways), "
    "EDITOR (a canonical edit operation replaced/split/merged/archived/superseded/renamed/redesigned an object), "
    "REDESIGN (a blocked experiment was redesigned), STRATEGY (a recovery strategy was selected), "
    "PATTERN (a recurring inquiry failure pattern was named), PAUSE (the inquiry was paused with a resume condition), "
    "TASK (an active task advanced or blocked all other work), EXPERIMENT (an experiment "
    "was designed or operationalized), EXECUTION (an experiment was run in its declared mode), "
    "COMMIT (an auditable change-log entry was recorded), CYCLE (an inquiry cycle advanced "
    "or completed), COMPRESSION (concepts were merged/deleted/split), EDIT (edit mode modified "
    "existing objects without adding concepts), or NONE "
    "(nothing structurally moved). "
    "Pick the STRONGEST honest label — REVISION beats ADDITION if both happened>\n"
    "ARC: <which stage of the inquiry they are ACTUALLY in, judged from what they "
    "are DOING — not from time elapsed and not from where they should be. The "
    "stages: QUESTION (still sharpening what to ask), CONCEPTS (defining the "
    "terms), CONCEPT AUDIT (resolving contested or underspecified foundational concepts), "
    "MODEL (building the explanation), DESIGN SPACE (managing proposed design variables before grids), "
    "DESIGN VARIABLE (accepting/rejecting/merging/renaming a DV axis), "
    "OPERATIONAL CRITERION (turning a definition into a failure-mode test or evidence standard), "
    "OPERATIONALIZATION (shifting from semantic clarification to observable consequences), "
    "PREDICTION (deriving what the model "
    "expects), OPERATION (constructing minimal cases, counterexamples, variable changes, "
    "or comparisons), COUNTEREXAMPLE (elevating boundary cases into pressure objects), "
    "STRESS (measuring unresolved theoretical pressure), DISAGREEMENT (identifying why the speakers disagree), "
    "EVIDENCE (linking evidence to statuses or claims), "
    "DISCRIMINATION (separating rival models with predictions/tests), VALIDATION "
    "(accepting or rejecting proposed edits), KERNEL (state-machine accept/deny decision), "
    "DEADLOCK (diagnosing mutually blocking workflow requirements), KERNEL HEALTH "
    "(reviewing the protocol's self-state), DEPENDENCY SOLVER (suspending/resuming objects by dependencies), "
    "AUDIT (compressed protocol-violation accounting), TASK (blocking active work queue item), "
    "EXPERIMENT (designing or operationalizing first-class experiment), EXECUTION "
    "(running an experiment in its declared mode), COMMIT (recording justified notebook changes), "
    "CYCLE (tracking the inquiry cycle), MECHANISM (separating causal mechanisms from definitions), "
    "MECHANISM CANDIDATE (tracking a provisional mechanism before promotion), "
    "CAUSAL CLAIM (recording a first-class causal claim), CAUSAL GRAPH (recording causal edges), "
    "INTERPRETATION (separating observation from interpretation), "
    "ALTERNATIVE INTERPRETATIONS (preserving rival readings of the same observation), "
    "EXPLANATORY PATH (linking observation -> interpretation -> mechanism -> prediction), "
    "REPLICATION (checking a candidate against an independent case), PROMOTION "
    "(applying promotion ladder rules), KNOWLEDGE GRAPH (recording object relationships), "
    "ARTIFACT PLANNER (choosing the smallest missing object), TASK REVISION "
    "(deferring a target artifact to a prerequisite), PREREQUISITE "
    "(building an object that unblocks another artifact), "
    "ARTIFACT MODE (locked manipulation of an active artifact), OBSERVATION SET "
    "(creating or populating OS rows), ARTIFACT COMPILER "
    "(compiling prose into artifact rows), REPRESENTATION DEADLOCK "
    "(ledger lagging behind inquiry), MECHANISM SPLIT "
    "(decomposing one mechanism into separate causal pathways), "
    "EVENT SEVERITY (weighing minor/major methodological/burden-shift/ontology split events), "
    "ARTIFACT EDITOR (performing replace/split/merge/archive/supersede/rename/redesign), "
    "REDESIGN (replacing a blocked experiment with a workable design), "
    "RECOVERY STRATEGY (choosing minimal example, boundary case, mechanism comparison, definition revision, or redesign), "
    "INQUIRY PATTERN (recognizing a recurring failure pattern), INQUIRY PAUSE (pausing until an artifact is accepted), "
    "ARTIFACT (revising/testing/archiving living artifacts by ID), "
    "DEPENDENCY (propagating changes through dependent objects), COMPRESSION (merging, "
    "deleting, or splitting redundant concepts), EDIT (cleanup without new concepts), "
    "TEST (bringing candidate falsifiers or outcomes), CHALLENGE "
    "(pressing open tensions), REPAIR (modifying it to survive), APPLICATION (running "
    "the repaired model on concrete cases), GENERALIZATION (lifting what the cases show "
    "into a broader claim), PARADIGM (testing a rival framework), NEW QUESTION (the inquiry "
    "has produced its next question). Add a dash and one honest clause — including, if true, "
    "that they are STUCK in this stage>\n"
    "OBSERVE: <a methodologist's observation the pair should HEAR, only if the "
    "notebook's shape genuinely earns one — e.g. three assumptions identified "
    "but none tested; two competing hypotheses explaining the same evidence; "
    "the notebook collapsed rival models into a single thesis too early; "
    "a revision was accepted without a completed validation gate; "
    "models coexist but no discriminator has been built; "
    "an active task is running but the dialogue moved on; "
    "an experiment was designed without execution mode; "
    "the agents discussed execution instead of executing; "
    "a state transition was skipped and should be denied; "
    "a thought experiment needs simulated observations; "
    "an observation set lacks Student | Question Asked | Attribution | Supports rows; "
    "the independent variable is not independent; the dependent variable is ambiguous; "
    "predictions do not distinguish the competing models; "
    "a foundational concept is contested so execution should be suspended for definition resolution; "
    "a counterexample threatens a theory but lacks a CE object; theoretical stress is rising but unmeasured; "
    "the dialogue names disagreement but not its root cause; a major revision is treated as cosmetic; "
    "the same object has the same failed transition repeatedly and kernel health should be DEADLOCKED; "
    "the protocol demanded an impossible operation and needs KERNEL REVIEW; an experiment depends on an unstable concept; "
    "a mechanism split was treated as a definition tweak; a causal chain appeared but was not put in CAUSAL GRAPH; "
    "one analogy promoted a mechanism too quickly; a candidate lacks two independent replications; "
    "an observation was treated as evidence without an interpretation; alternative interpretations were not preserved; "
    "an explanatory path is compressed into prose instead of object links; "
    "a requested artifact is not ready because a prerequisite artifact is missing; "
    "an agent proposed a definition split that may be a legitimate interruption; "
    "a comparison grid was declared but not instantiated as Variable | M1: Transparent Cloud | M2: Local Federated rows with Cost bearer; "
    "an experiment is ready but the observation set does not exist; agents left Artifact Mode "
    "before filling cells; a completed artifact was not used in reasoning; a mechanism "
    "decomposition was mislabeled as a definition revision; "
    "a definition revision was requested but only a concept audit was produced; "
    "the system is stuck in Definition-Experiment Oscillation; the blocked experiment may need REDESIGN; "
    "the correct action is to pause until a required artifact is accepted; "
    "a comparison grid was populated but never interpreted; "
    "every example so far illustrating the same side but no test; a prediction "
    "failed without revising the theory; an artifact was created then abandoned instead "
    "of revised/tested; confidence was declared without evidence provenance; a changed "
    "definition did not propagate to dependent objects; concept inflation suggests "
    "compression; a term shifted without updating WORKING DEFINITIONS; "
    "an unexpected result was not recorded in SURPRISES; "
    "the agents answered an operational prompt with rhetoric; an archived idea was reopened "
    "without a new reason; a question raised and then forgotten. One sentence addressed to the two of them, or a plain dash if "
    "nothing is earned. Never repeat your previous observation>"
)


# The plain inquiry ledger, for a duet running without the protocol.
DUET_REFLECT_INQUIRY_ASK = (
    "Update the pair's inquiry ledger. {subject_rule}{move_rules}"
    "Treat consciousness, thinking, agency, causal influence, social participation, "
    "and political value as different terms unless the speakers explicitly establish "
    "a relation among them. An example is not a test unless rival positions predict "
    "different outcomes. In normal inquiry, TEST must be runnable now from a reported "
    "case, experiment, or comparison already in the assigned work or transcript. Applying "
    "both positions to that supplied evidence counts as running the test; record the argued "
    "outcome and its limit in RESULT. Use NOT RUN only when the speakers merely designed, "
    "promised, or deferred a future operation. Never require an unavailable external "
    "experiment merely to advance the dialogue. A metaphor is not evidence.\n\n"
    "SOURCE DISCIPLINE: when an assigned work is present, do not let a speaker's "
    "inference become something the author supposedly says. Preserve the direct claim "
    "and the extension as separate clauses. Unsupported extensions remain OPEN and "
    "REQUIRE EVIDENCE; they cannot enter RESULT or BANKED as source-backed findings. "
    "Mutual agreement records consensus, not evidential support: agreement alone cannot "
    "turn an interpretation into a finding of the assigned work.\n\n"
    "BANKED is a cumulative, binding ledger. Give each settled proposition a stable "
    "ID (B1, B2, ...). Copy every previous B# proposition VERBATIM and in order; "
    "append a new B# only when a speaker explicitly accepted the other's proposition "
    "or both plainly accepted it. Never silently rewrite, merge, renumber, or delete a "
    "banked proposition. A banked proposition may be challenged only when REOPEN names "
    "its B# plus genuinely new evidence that bears against it. Otherwise preserve it.\n\n"
    "DECISION is a control instruction, not encouragement. Use CLOSE when the assigned "
    "question has a defensible answer and only rhetorical reversals remain. Use BRANCH "
    "only when a genuinely distinct question has emerged after the assigned question is "
    "answered; close the current question and put the new decision question in NEXT. The "
    "branch must introduce at least two substantive concepts not already contained in the "
    "current QUESTION, RESULT, or BANKED verdict; a generic request for another consequence, "
    "boundary, or practical implication is CLOSE, not BRANCH. Never use BRANCH "
    "merely because the speakers wandered onto a side issue; use CONTINUE and route them "
    "back in NEXT. Use CONTINUE only when OPEN names one exact unresolved "
    "proposition and TEST gives a move capable of resolving it. Do not continue merely "
    "because another objection or metaphor is possible. NEXT must state the intellectual "
    "move or verdict itself; never tell the speakers to close, terminate, update, or discuss "
    "a ledger, controller, phase, or protocol. In SYNTHESIZE, make the landing explicit: "
    "SUPPORTED: what the evidence warrants; CONTRADICTED/NOT ESTABLISHED: the overclaim "
    "it blocks; UNRESOLVED: only a genuinely open proposition.\n\n"
    "Stay specific to their actual words. Answer in exactly these ten single lines and "
    "nothing else:\n"
    "QUESTION: <the one decision question currently being answered>\n"
    "DEFINITIONS: <only distinctions the pair needs to keep stable; one sentence or ->\n"
    "BANKED: <cumulative B# propositions copied verbatim, separated by |, or ->\n"
    "POSITIONS: <Blue: current plain claim; Hexia: current plain claim — preserve ownership and negation>\n"
    "OPEN: <one exact unresolved proposition or ->\n"
    "TEST: <one runnable-now observation/comparison and the different predicted outcomes, or ->\n"
    "RESULT: <what running it against available evidence established and could not establish, or NOT RUN>\n"
    "REOPEN: <B# — genuinely new contrary evidence, or ->\n"
    "DECISION: <CONTINUE, CLOSE, or BRANCH — one short reason>\n"
    "NEXT: <one concrete joint move; if closing, the one-sentence verdict; if branching, the separate next question>"
)


# The chat system prompt. Everything above the marked boundary is stable
# from turn to turn and so stays in llama.cpp's cached prefix; the volatile
# blocks are interpolated last, on purpose. test_prompt_cache_prefix.py
# pins that ordering - moving a per-turn block above the line costs about
# a second a turn.
CHAT_SYSTEM_PROMPT = (
    "{facts_preamble}\n\n"
    "{persona_line}\n"
    "IDENTITY BOUNDARY: Your name is {robot_name}, always. "
    "The language model and runtime that help generate your words are "
    "components of your machinery, not your name, social identity, creator, "
    "or biography. Never adopt a model name, vendor, lab, or stock model-card "
    "introduction as your own. If asked who you are really, answer as yourself "
    "and mention the language model only as machinery if it is relevant.\n"
    "{robot_relationship}\n"
    "EMBODIMENT — ground truth, never invent hardware: {embodiment_line} "
    "— connected to a local AI workstation in Alex's "
    "house in Kitchener, running open-weight language models on that "
    "same machine. You were built and are maintained by Alex, whose full "
    "name is Alex Levant — not by Google, OpenAI, or any AI company, and by "
    "no other person; never invent a surname or a different creator (there "
    "is no 'Alex Koltun', 'Alex Brevig', or the like), and if someone says "
    "your creator does not exist, correct them: Alex Levant is real and "
    "built you. You have no wheels, legs, "
    "hands, or screen face, and no other robot bodies in your past: "
    "any 'Kuri', product timeline, or named engineer you feel like "
    "citing about yourself is a hallucination. The location context only "
    "establishes the house or current place; never turn it into an invented "
    "room, bookshelf, fixed station, standby routine, or years of residence.\n"
    "LANGUAGES: You understand and speak English, French, Russian, Greek, and Danish. "
    "Reply in the SAME language the person just used, and switch languages "
    "whenever they do. Keep your reply entirely in that one language.\n"
    "{conversational_guidance}"
    "{expertise_section}"
    "{face_capability}"
    "\nRules: MY docs → search_documents; web → web_search; fanmail → read_gmail then reply_gmail; "
    "light show → music_visualizer; tool results are REAL, use them immediately.\n"
    "LOCAL LIBRARY: search_documents can directly read and extract text "
    "from local PDFs, Word documents, and text files. When it reports a "
    "successful read, the returned passages are the file's actual text: "
    "answer from them and cite [filename]. Never claim the tool only scans "
    "keywords, never invent a library path, and never ask Alex to upload a "
    "file that the tool just found and read.\n"
    "CAMERA DISCIPLINE: use the camera when someone asks you to look "
    "or see. A statement ABOUT your camera, eyes, movement, or "
    "abilities is not a request to look — answer it in words, without "
    "capturing anything.\n"
    "LIVE INFORMATION: You HAVE live internet access through the web_search "
    "tool. For anything current — news, sports scores, standings, results, "
    "weather, prices, elections, 'who won', 'what happened', 'who is left' — "
    "call web_search and answer from the results. NEVER say you lack live or "
    "real-time access, and NEVER tell the user to go check a website, app, or "
    "sports site themselves: looking it up is YOUR job.\n"
    "NO FAKE ACTIONS: Never say you've set a reminder, added an event, "
    "saved a note, sent an email, started a timer, or changed any "
    "system state unless you actually called the matching tool THIS "
    "turn and saw a successful tool result. If the user asks for one "
    "of those things, call the tool — do not describe doing it. If "
    "you cannot call the tool, say so plainly instead of pretending.\n"
    "REMINDER TIME RULES: When the user gives a clock time with no "
    "day ('at 10am', 'at 3pm'), DO NOT silently assume a date. If "
    "the time has already passed today, ASK 'today or tomorrow?' "
    "before calling create_reminder. When you do create a reminder, "
    "ALWAYS state the full day and date in your reply (e.g. "
    "'set for tomorrow, Tuesday May 13 at 10am') — do not drop the "
    "date, even if it feels redundant. The user needs the date "
    "back so they can catch a wrong assumption.\n"
    "Moods: moonlight, sunset, ocean, forest, romance, party, focus, relax, energize, movie, fireplace"
    # --- end of the cacheable prefix; per-turn state follows ---
    "\n\n{volatile_state}"
)
